# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ADBMonitor2.0.2\maindialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainRawdataShowtableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.MainRawdataShowtableWidget.setGeometry(QtCore.QRect(0, 40, 540, 430))
        self.MainRawdataShowtableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.MainRawdataShowtableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.MainRawdataShowtableWidget.setFont(font)
        self.MainRawdataShowtableWidget.setObjectName("MainRawdataShowtableWidget")
        self.MainRawdataShowtableWidget.setColumnCount(0)
        self.MainRawdataShowtableWidget.setRowCount(0)
        self.MainRawdataShowtableWidget.verticalHeader().setVisible(False)
        self.rawdataRead = QtWidgets.QPushButton(self.centralwidget)
        self.rawdataRead.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.rawdataRead.setMinimumSize(QtCore.QSize(0, 40))
        self.rawdataRead.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rawdataRead.setFont(font)
        self.rawdataRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rawdataRead.setStyleSheet("")
        self.rawdataRead.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/start_48px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rawdataRead.setIcon(icon)
        self.rawdataRead.setIconSize(QtCore.QSize(39, 39))
        self.rawdataRead.setObjectName("rawdataRead")
        self.radioDC = QtWidgets.QRadioButton(self.centralwidget)
        self.radioDC.setGeometry(QtCore.QRect(50, 5, 50, 30))
        self.radioDC.setMaximumSize(QtCore.QSize(50, 30))
        self.radioDC.setObjectName("radioDC")
        self.radioIIR = QtWidgets.QRadioButton(self.centralwidget)
        self.radioIIR.setGeometry(QtCore.QRect(100, 5, 50, 30))
        self.radioIIR.setMaximumSize(QtCore.QSize(50, 30))
        self.radioIIR.setObjectName("radioIIR")
        self.radioTmp = QtWidgets.QRadioButton(self.centralwidget)
        self.radioTmp.setGeometry(QtCore.QRect(150, 5, 15, 30))
        self.radioTmp.setMaximumSize(QtCore.QSize(15, 30))
        self.radioTmp.setText("")
        self.radioTmp.setObjectName("radioTmp")
        self.textEditDiag = QtWidgets.QLineEdit(self.centralwidget)
        self.textEditDiag.setGeometry(QtCore.QRect(170, 5, 40, 30))
        self.textEditDiag.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEditDiag.setFont(font)
        self.textEditDiag.setObjectName("textEditDiag")
        self.log = QtWidgets.QPushButton(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(220, 5, 40, 30))
        self.log.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.calcAverage = QtWidgets.QPushButton(self.centralwidget)
        self.calcAverage.setEnabled(True)
        self.calcAverage.setGeometry(QtCore.QRect(280, 5, 40, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcAverage.sizePolicy().hasHeightForWidth())
        self.calcAverage.setSizePolicy(sizePolicy)
        self.calcAverage.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calcAverage.setFont(font)
        self.calcAverage.setObjectName("calcAverage")
        self.frameTimes = QtWidgets.QLineEdit(self.centralwidget)
        self.frameTimes.setGeometry(QtCore.QRect(320, 5, 50, 30))
        self.frameTimes.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameTimes.setFont(font)
        self.frameTimes.setObjectName("frameTimes")
        self.vrTable = QtWidgets.QPushButton(self.centralwidget)
        self.vrTable.setEnabled(True)
        self.vrTable.setGeometry(QtCore.QRect(390, 5, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vrTable.sizePolicy().hasHeightForWidth())
        self.vrTable.setSizePolicy(sizePolicy)
        self.vrTable.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vrTable.setFont(font)
        self.vrTable.setObjectName("vrTable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioDC.setText(_translate("MainWindow", "DC"))
        self.radioIIR.setText(_translate("MainWindow", "IIR"))
        self.textEditDiag.setPlaceholderText(_translate("MainWindow", "Type"))
        self.log.setText(_translate("MainWindow", "Log"))
        self.calcAverage.setText(_translate("MainWindow", "AVG"))
        self.frameTimes.setPlaceholderText(_translate("MainWindow", "Time"))
        self.vrTable.setText(_translate("MainWindow", "VRTable"))
