# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ADBMonitor2.0.2\maindialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rawdataRead = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.rawdataRead.setMinimumSize(QtCore.QSize(0, 40))
        self.rawdataRead.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rawdataRead.setFont(font)
        self.rawdataRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rawdataRead.setStyleSheet("")
        self.rawdataRead.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/start_48px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rawdataRead.setIcon(icon)
        self.rawdataRead.setIconSize(QtCore.QSize(39, 39))
        self.rawdataRead.setObjectName("rawdataRead")
        self.horizontalLayout.addWidget(self.rawdataRead)
        self.radioDC = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioDC.setMaximumSize(QtCore.QSize(50, 30))
        self.radioDC.setObjectName("radioDC")
        self.horizontalLayout.addWidget(self.radioDC)
        self.radioIIR = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioIIR.setMaximumSize(QtCore.QSize(50, 30))
        self.radioIIR.setObjectName("radioIIR")
        self.horizontalLayout.addWidget(self.radioIIR)
        self.radioTmp = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioTmp.setMaximumSize(QtCore.QSize(15, 30))
        self.radioTmp.setText("")
        self.radioTmp.setObjectName("radioTmp")
        self.horizontalLayout.addWidget(self.radioTmp)
        self.textEditDiag = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.textEditDiag.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEditDiag.setFont(font)
        self.textEditDiag.setObjectName("textEditDiag")
        self.horizontalLayout.addWidget(self.textEditDiag)
        self.log = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.log.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.horizontalLayout.addWidget(self.log)
        self.recalled = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.recalled.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recalled.sizePolicy().hasHeightForWidth())
        self.recalled.setSizePolicy(sizePolicy)
        self.recalled.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.recalled.setFont(font)
        self.recalled.setObjectName("recalled")
        self.horizontalLayout.addWidget(self.recalled)
        self.timeLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.timeLineEdit.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timeLineEdit.setFont(font)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.horizontalLayout.addWidget(self.timeLineEdit)
        self.MainRawdataShowtableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.MainRawdataShowtableWidget.setGeometry(QtCore.QRect(0, 50, 540, 430))
        self.MainRawdataShowtableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.MainRawdataShowtableWidget.setMaximumSize(QtCore.QSize(750, 550))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.MainRawdataShowtableWidget.setFont(font)
        self.MainRawdataShowtableWidget.setObjectName("MainRawdataShowtableWidget")
        self.MainRawdataShowtableWidget.setColumnCount(0)
        self.MainRawdataShowtableWidget.setRowCount(0)
        self.MainRawdataShowtableWidget.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioDC.setText(_translate("MainWindow", "DC"))
        self.radioIIR.setText(_translate("MainWindow", "IIR"))
        self.textEditDiag.setPlaceholderText(_translate("MainWindow", "Type"))
        self.log.setText(_translate("MainWindow", "Log"))
        self.recalled.setText(_translate("MainWindow", "ReL"))
        self.timeLineEdit.setPlaceholderText(_translate("MainWindow", "Time"))
