# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ADBMonitor2.0.2\uimonitor_init.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(590, 480)
        MainWindow.setMinimumSize(QtCore.QSize(590, 480))
        MainWindow.setMaximumSize(QtCore.QSize(590, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TabMainWindow = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.TabMainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TabMainWindow.setFont(font)
        self.TabMainWindow.setObjectName("TabMainWindow")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.touchInfoGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.touchInfoGroupBox.setGeometry(QtCore.QRect(0, 0, 221, 81))
        self.touchInfoGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.touchInfoGroupBox.setObjectName("touchInfoGroupBox")
        self.touchInfoRXLineEdit = QtWidgets.QLineEdit(self.touchInfoGroupBox)
        self.touchInfoRXLineEdit.setGeometry(QtCore.QRect(30, 20, 50, 20))
        self.touchInfoRXLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoRXLineEdit.setMaxLength(2)
        self.touchInfoRXLineEdit.setObjectName("touchInfoRXLineEdit")
        self.touchInfoTXLineEdit = QtWidgets.QLineEdit(self.touchInfoGroupBox)
        self.touchInfoTXLineEdit.setGeometry(QtCore.QRect(30, 45, 50, 20))
        self.touchInfoTXLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoTXLineEdit.setMaxLength(2)
        self.touchInfoTXLineEdit.setObjectName("touchInfoTXLineEdit")
        self.touchInfoRXLabel = QtWidgets.QLabel(self.touchInfoGroupBox)
        self.touchInfoRXLabel.setGeometry(QtCore.QRect(10, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.touchInfoRXLabel.setFont(font)
        self.touchInfoRXLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoRXLabel.setObjectName("touchInfoRXLabel")
        self.touchInfoTXLabel = QtWidgets.QLabel(self.touchInfoGroupBox)
        self.touchInfoTXLabel.setGeometry(QtCore.QRect(10, 45, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.touchInfoTXLabel.setFont(font)
        self.touchInfoTXLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoTXLabel.setObjectName("touchInfoTXLabel")
        self.touchInfoRexYLabel = QtWidgets.QLabel(self.touchInfoGroupBox)
        self.touchInfoRexYLabel.setGeometry(QtCore.QRect(100, 45, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.touchInfoRexYLabel.setFont(font)
        self.touchInfoRexYLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoRexYLabel.setObjectName("touchInfoRexYLabel")
        self.touchInfoRexXLabel = QtWidgets.QLabel(self.touchInfoGroupBox)
        self.touchInfoRexXLabel.setGeometry(QtCore.QRect(100, 20, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.touchInfoRexXLabel.setFont(font)
        self.touchInfoRexXLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoRexXLabel.setObjectName("touchInfoRexXLabel")
        self.touchInfoResXLineEdit = QtWidgets.QLineEdit(self.touchInfoGroupBox)
        self.touchInfoResXLineEdit.setGeometry(QtCore.QRect(150, 20, 60, 20))
        self.touchInfoResXLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoResXLineEdit.setMaxLength(4)
        self.touchInfoResXLineEdit.setObjectName("touchInfoResXLineEdit")
        self.touchInfoResYLineEdit = QtWidgets.QLineEdit(self.touchInfoGroupBox)
        self.touchInfoResYLineEdit.setGeometry(QtCore.QRect(150, 45, 60, 20))
        self.touchInfoResYLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.touchInfoResYLineEdit.setMaxLength(4)
        self.touchInfoResYLineEdit.setObjectName("touchInfoResYLineEdit")
        self.settingsGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.settingsGroupBox.setGeometry(QtCore.QRect(0, 80, 580, 350))
        self.settingsGroupBox.setBaseSize(QtCore.QSize(0, 0))
        self.settingsGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.pathV1RadioButton = QtWidgets.QRadioButton(self.settingsGroupBox)
        self.pathV1RadioButton.setGeometry(QtCore.QRect(130, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathV1RadioButton.setFont(font)
        self.pathV1RadioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pathV1RadioButton.setMouseTracking(True)
        self.pathV1RadioButton.setTabletTracking(False)
        self.pathV1RadioButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pathV1RadioButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathV1RadioButton.setObjectName("pathV1RadioButton")
        self.pathV2RadioButton = QtWidgets.QRadioButton(self.settingsGroupBox)
        self.pathV2RadioButton.setGeometry(QtCore.QRect(170, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathV2RadioButton.setFont(font)
        self.pathV2RadioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pathV2RadioButton.setMouseTracking(True)
        self.pathV2RadioButton.setTabletTracking(False)
        self.pathV2RadioButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pathV2RadioButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathV2RadioButton.setObjectName("pathV2RadioButton")
        self.pathDriVerLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathDriVerLabel.setGeometry(QtCore.QRect(10, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pathDriVerLabel.setFont(font)
        self.pathDriVerLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDriVerLabel.setObjectName("pathDriVerLabel")
        self.pathDiagLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathDiagLabel.setGeometry(QtCore.QRect(0, 50, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathDiagLabel.setFont(font)
        self.pathDiagLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDiagLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathDiagLabel.setObjectName("pathDiagLabel")
        self.pathRegLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathRegLabel.setGeometry(QtCore.QRect(0, 73, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathRegLabel.setFont(font)
        self.pathRegLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathRegLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathRegLabel.setObjectName("pathRegLabel")
        self.pathResetLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathResetLabel.setGeometry(QtCore.QRect(0, 96, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathResetLabel.setFont(font)
        self.pathResetLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathResetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathResetLabel.setObjectName("pathResetLabel")
        self.pathIntenLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathIntenLabel.setGeometry(QtCore.QRect(0, 119, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathIntenLabel.setFont(font)
        self.pathIntenLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathIntenLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathIntenLabel.setObjectName("pathIntenLabel")
        self.pathDiagarrLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathDiagarrLabel.setGeometry(QtCore.QRect(0, 142, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathDiagarrLabel.setFont(font)
        self.pathDiagarrLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDiagarrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathDiagarrLabel.setObjectName("pathDiagarrLabel")
        self.pathSenseonoffLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathSenseonoffLabel.setGeometry(QtCore.QRect(0, 165, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathSenseonoffLabel.setFont(font)
        self.pathSenseonoffLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathSenseonoffLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathSenseonoffLabel.setObjectName("pathSenseonoffLabel")
        self.pathStackLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathStackLabel.setGeometry(QtCore.QRect(0, 199, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathStackLabel.setFont(font)
        self.pathStackLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathStackLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathStackLabel.setObjectName("pathStackLabel")
        self.pathDebugLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathDebugLabel.setGeometry(QtCore.QRect(0, 231, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathDebugLabel.setFont(font)
        self.pathDebugLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDebugLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathDebugLabel.setObjectName("pathDebugLabel")
        self.pathSelftestLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathSelftestLabel.setGeometry(QtCore.QRect(0, 254, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathSelftestLabel.setFont(font)
        self.pathSelftestLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathSelftestLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathSelftestLabel.setObjectName("pathSelftestLabel")
        self.pathFlashdumpLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathFlashdumpLabel.setGeometry(QtCore.QRect(0, 277, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathFlashdumpLabel.setFont(font)
        self.pathFlashdumpLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathFlashdumpLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathFlashdumpLabel.setObjectName("pathFlashdumpLabel")
        self.pathHXFolderLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathHXFolderLabel.setGeometry(QtCore.QRect(0, 307, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathHXFolderLabel.setFont(font)
        self.pathHXFolderLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathHXFolderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathHXFolderLabel.setObjectName("pathHXFolderLabel")
        self.pathFWLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathFWLabel.setGeometry(QtCore.QRect(0, 330, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pathFWLabel.setFont(font)
        self.pathFWLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathFWLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathFWLabel.setObjectName("pathFWLabel")
        self.pathDiagLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathDiagLineEdit.setGeometry(QtCore.QRect(90, 50, 400, 20))
        self.pathDiagLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDiagLineEdit.setObjectName("pathDiagLineEdit")
        self.pathRegLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathRegLineEdit.setGeometry(QtCore.QRect(90, 73, 400, 20))
        self.pathRegLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathRegLineEdit.setObjectName("pathRegLineEdit")
        self.pathResetLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathResetLineEdit.setGeometry(QtCore.QRect(90, 96, 400, 20))
        self.pathResetLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathResetLineEdit.setObjectName("pathResetLineEdit")
        self.pathIntenLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathIntenLineEdit.setGeometry(QtCore.QRect(90, 119, 400, 20))
        self.pathIntenLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathIntenLineEdit.setObjectName("pathIntenLineEdit")
        self.pathDiagarrLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathDiagarrLineEdit.setGeometry(QtCore.QRect(90, 142, 400, 20))
        self.pathDiagarrLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDiagarrLineEdit.setObjectName("pathDiagarrLineEdit")
        self.pathSenseonoffLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathSenseonoffLineEdit.setGeometry(QtCore.QRect(90, 165, 400, 20))
        self.pathSenseonoffLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathSenseonoffLineEdit.setObjectName("pathSenseonoffLineEdit")
        self.pathStackLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathStackLineEdit.setGeometry(QtCore.QRect(90, 199, 400, 20))
        self.pathStackLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathStackLineEdit.setObjectName("pathStackLineEdit")
        self.pathDebugLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathDebugLineEdit.setGeometry(QtCore.QRect(90, 231, 400, 20))
        self.pathDebugLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathDebugLineEdit.setObjectName("pathDebugLineEdit")
        self.pathSelftestLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathSelftestLineEdit.setGeometry(QtCore.QRect(90, 254, 400, 20))
        self.pathSelftestLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathSelftestLineEdit.setObjectName("pathSelftestLineEdit")
        self.pathFlashdumpLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathFlashdumpLineEdit.setGeometry(QtCore.QRect(90, 277, 400, 20))
        self.pathFlashdumpLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathFlashdumpLineEdit.setObjectName("pathFlashdumpLineEdit")
        self.pathHXFolderLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathHXFolderLineEdit.setGeometry(QtCore.QRect(90, 307, 400, 20))
        self.pathHXFolderLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathHXFolderLineEdit.setObjectName("pathHXFolderLineEdit")
        self.pathFWLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.pathFWLineEdit.setGeometry(QtCore.QRect(90, 330, 400, 20))
        self.pathFWLineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.pathFWLineEdit.setObjectName("pathFWLineEdit")
        self.pathConmmentLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.pathConmmentLabel.setGeometry(QtCore.QRect(210, 20, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pathConmmentLabel.setFont(font)
        self.pathConmmentLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.pathConmmentLabel.setObjectName("pathConmmentLabel")
        self.groupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox.setGeometry(QtCore.QRect(230, 0, 351, 81))
        self.groupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.groupBox.setObjectName("groupBox")
        self.conmment = QtWidgets.QLabel(self.groupBox)
        self.conmment.setGeometry(QtCore.QRect(0, 55, 95, 15))
        self.conmment.setAutoFillBackground(False)
        self.conmment.setStyleSheet("color: rgb(0, 0, 0);")
        self.conmment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conmment.setObjectName("conmment")
        self.settingsProComboBox = QtWidgets.QComboBox(self.groupBox)
        self.settingsProComboBox.setGeometry(QtCore.QRect(100, 20, 160, 25))
        self.settingsProComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsProComboBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.settingsProComboBox.setObjectName("settingsProComboBox")
        self.pathSavePushButton = QtWidgets.QPushButton(self.groupBox)
        self.pathSavePushButton.setGeometry(QtCore.QRect(100, 50, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pathSavePushButton.setFont(font)
        self.pathSavePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pathSavePushButton.setWhatsThis("")
        self.pathSavePushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.pathSavePushButton.setObjectName("pathSavePushButton")
        self.conmment_2 = QtWidgets.QLabel(self.groupBox)
        self.conmment_2.setGeometry(QtCore.QRect(0, 25, 95, 15))
        self.conmment_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.conmment_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conmment_2.setObjectName("conmment_2")
        self.settingRemove = QtWidgets.QPushButton(self.groupBox)
        self.settingRemove.setGeometry(QtCore.QRect(270, 50, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.settingRemove.setFont(font)
        self.settingRemove.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.settingRemove.setObjectName("settingRemove")
        self.settingRemoveLabel = QtWidgets.QLabel(self.groupBox)
        self.settingRemoveLabel.setGeometry(QtCore.QRect(270, 20, 75, 20))
        self.settingRemoveLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.settingRemoveLabel.setObjectName("settingRemoveLabel")
        self.TabMainWindow.addTab(self.tabSettings, "")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.wifiGroupBox = QtWidgets.QGroupBox(self.tabOptions)
        self.wifiGroupBox.setGeometry(QtCore.QRect(0, 0, 580, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wifiGroupBox.setFont(font)
        self.wifiGroupBox.setToolTipDuration(-1)
        self.wifiGroupBox.setAutoFillBackground(False)
        self.wifiGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.wifiGroupBox.setObjectName("wifiGroupBox")
        self.wifiConnect = QtWidgets.QPushButton(self.wifiGroupBox)
        self.wifiConnect.setGeometry(QtCore.QRect(10, 15, 90, 30))
        self.wifiConnect.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wifiConnect.setFont(font)
        self.wifiConnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiConnect.setFlat(False)
        self.wifiConnect.setObjectName("wifiConnect")
        self.wifiDisconnect = QtWidgets.QPushButton(self.wifiGroupBox)
        self.wifiDisconnect.setGeometry(QtCore.QRect(105, 15, 90, 30))
        self.wifiDisconnect.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wifiDisconnect.setFont(font)
        self.wifiDisconnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiDisconnect.setCheckable(False)
        self.wifiDisconnect.setObjectName("wifiDisconnect")
        self.wifiReconnect = QtWidgets.QPushButton(self.wifiGroupBox)
        self.wifiReconnect.setGeometry(QtCore.QRect(200, 15, 90, 30))
        self.wifiReconnect.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wifiReconnect.setFont(font)
        self.wifiReconnect.setStyleSheet("color: rgb(0, 0, 0);")
        self.wifiReconnect.setCheckable(False)
        self.wifiReconnect.setObjectName("wifiReconnect")
        self.wifiStatus = QtWidgets.QLabel(self.wifiGroupBox)
        self.wifiStatus.setGeometry(QtCore.QRect(290, 15, 96, 30))
        self.wifiStatus.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.wifiStatus.setFont(font)
        self.wifiStatus.setStyleSheet("color: rgb(255, 0, 0);")
        self.wifiStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.wifiStatus.setWordWrap(False)
        self.wifiStatus.setObjectName("wifiStatus")
        self.root = QtWidgets.QPushButton(self.wifiGroupBox)
        self.root.setGeometry(QtCore.QRect(390, 15, 90, 30))
        self.root.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.root.setFont(font)
        self.root.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.root.setObjectName("root")
        self.adbStatus = QtWidgets.QLabel(self.wifiGroupBox)
        self.adbStatus.setGeometry(QtCore.QRect(480, 15, 100, 30))
        self.adbStatus.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.adbStatus.setFont(font)
        self.adbStatus.setStyleSheet("color: rgb(255, 0, 0);")
        self.adbStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.adbStatus.setWordWrap(False)
        self.adbStatus.setObjectName("adbStatus")
        self.adbGroupBox = QtWidgets.QGroupBox(self.tabOptions)
        self.adbGroupBox.setGeometry(QtCore.QRect(0, 50, 580, 86))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adbGroupBox.setFont(font)
        self.adbGroupBox.setToolTipDuration(-1)
        self.adbGroupBox.setAutoFillBackground(False)
        self.adbGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.adbGroupBox.setObjectName("adbGroupBox")
        self.homekey = QtWidgets.QPushButton(self.adbGroupBox)
        self.homekey.setGeometry(QtCore.QRect(10, 50, 90, 30))
        self.homekey.setMinimumSize(QtCore.QSize(0, 0))
        self.homekey.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homekey.setFont(font)
        self.homekey.setStyleSheet("color: rgb(0, 0, 0);")
        self.homekey.setObjectName("homekey")
        self.reboot = QtWidgets.QPushButton(self.adbGroupBox)
        self.reboot.setGeometry(QtCore.QRect(390, 15, 90, 30))
        self.reboot.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reboot.setFont(font)
        self.reboot.setStyleSheet("color: rgb(0, 0, 0);")
        self.reboot.setObjectName("reboot")
        self.volDown = QtWidgets.QPushButton(self.adbGroupBox)
        self.volDown.setGeometry(QtCore.QRect(295, 50, 90, 30))
        self.volDown.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.volDown.setFont(font)
        self.volDown.setStyleSheet("color: rgb(0, 0, 0);")
        self.volDown.setObjectName("volDown")
        self.backkey = QtWidgets.QPushButton(self.adbGroupBox)
        self.backkey.setGeometry(QtCore.QRect(105, 50, 90, 30))
        self.backkey.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backkey.setFont(font)
        self.backkey.setStyleSheet("color: rgb(0, 0, 0);")
        self.backkey.setObjectName("backkey")
        self.volUp = QtWidgets.QPushButton(self.adbGroupBox)
        self.volUp.setGeometry(QtCore.QRect(200, 50, 90, 30))
        self.volUp.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.volUp.setFont(font)
        self.volUp.setStyleSheet("color: rgb(0, 0, 0);")
        self.volUp.setObjectName("volUp")
        self.powerKey = QtWidgets.QPushButton(self.adbGroupBox)
        self.powerKey.setGeometry(QtCore.QRect(105, 15, 90, 30))
        self.powerKey.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.powerKey.setFont(font)
        self.powerKey.setStyleSheet("color: rgb(0, 0, 0);")
        self.powerKey.setObjectName("powerKey")
        self.screenShot = QtWidgets.QPushButton(self.adbGroupBox)
        self.screenShot.setGeometry(QtCore.QRect(390, 50, 90, 30))
        self.screenShot.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.screenShot.setFont(font)
        self.screenShot.setStyleSheet("color: rgb(0, 0, 0);")
        self.screenShot.setObjectName("screenShot")
        self.openClosePoint = QtWidgets.QPushButton(self.adbGroupBox)
        self.openClosePoint.setGeometry(QtCore.QRect(200, 15, 90, 30))
        self.openClosePoint.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openClosePoint.setFont(font)
        self.openClosePoint.setStyleSheet("color: rgb(0, 0, 0);")
        self.openClosePoint.setObjectName("openClosePoint")
        self.opencmd = QtWidgets.QPushButton(self.adbGroupBox)
        self.opencmd.setGeometry(QtCore.QRect(295, 15, 90, 30))
        self.opencmd.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opencmd.setFont(font)
        self.opencmd.setStyleSheet("color: rgb(0, 0, 0);")
        self.opencmd.setObjectName("opencmd")
        self.hideShowVirtual = QtWidgets.QPushButton(self.adbGroupBox)
        self.hideShowVirtual.setGeometry(QtCore.QRect(10, 15, 90, 30))
        self.hideShowVirtual.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.hideShowVirtual.setFont(font)
        self.hideShowVirtual.setStyleSheet("color: rgb(0, 0, 0);")
        self.hideShowVirtual.setObjectName("hideShowVirtual")
        self.shutDown = QtWidgets.QPushButton(self.adbGroupBox)
        self.shutDown.setGeometry(QtCore.QRect(485, 15, 90, 30))
        self.shutDown.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shutDown.setFont(font)
        self.shutDown.setStyleSheet("color: rgb(0, 0, 0);")
        self.shutDown.setObjectName("shutDown")
        self.screenRecord = QtWidgets.QPushButton(self.adbGroupBox)
        self.screenRecord.setGeometry(QtCore.QRect(485, 50, 90, 30))
        self.screenRecord.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.screenRecord.setFont(font)
        self.screenRecord.setStyleSheet("color: rgb(0, 0, 0);")
        self.screenRecord.setObjectName("screenRecord")
        self.touchGroupBox = QtWidgets.QGroupBox(self.tabOptions)
        self.touchGroupBox.setGeometry(QtCore.QRect(0, 135, 580, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.touchGroupBox.setFont(font)
        self.touchGroupBox.setAutoFillBackground(False)
        self.touchGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.touchGroupBox.setObjectName("touchGroupBox")
        self.inten0 = QtWidgets.QPushButton(self.touchGroupBox)
        self.inten0.setGeometry(QtCore.QRect(485, 15, 90, 30))
        self.inten0.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inten0.setFont(font)
        self.inten0.setStyleSheet("color: rgb(0, 0, 0);")
        self.inten0.setObjectName("inten0")
        self.senseon = QtWidgets.QPushButton(self.touchGroupBox)
        self.senseon.setGeometry(QtCore.QRect(200, 15, 90, 30))
        self.senseon.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.senseon.setFont(font)
        self.senseon.setStyleSheet("color: rgb(0, 0, 0);")
        self.senseon.setObjectName("senseon")
        self.fwVersion = QtWidgets.QPushButton(self.touchGroupBox)
        self.fwVersion.setGeometry(QtCore.QRect(10, 15, 90, 30))
        self.fwVersion.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fwVersion.setFont(font)
        self.fwVersion.setStyleSheet("color: rgb(0, 0, 0);")
        self.fwVersion.setObjectName("fwVersion")
        self.selftest = QtWidgets.QPushButton(self.touchGroupBox)
        self.selftest.setGeometry(QtCore.QRect(295, 15, 90, 30))
        self.selftest.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selftest.setFont(font)
        self.selftest.setStyleSheet("color: rgb(0, 0, 0);")
        self.selftest.setObjectName("selftest")
        self.diagArr = QtWidgets.QPushButton(self.touchGroupBox)
        self.diagArr.setGeometry(QtCore.QRect(10, 50, 90, 30))
        self.diagArr.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.diagArr.setFont(font)
        self.diagArr.setStyleSheet("color: rgb(0, 0, 0);")
        self.diagArr.setObjectName("diagArr")
        self.flashDump = QtWidgets.QPushButton(self.touchGroupBox)
        self.flashDump.setGeometry(QtCore.QRect(390, 15, 90, 30))
        self.flashDump.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flashDump.setFont(font)
        self.flashDump.setStyleSheet("color: rgb(0, 0, 0);")
        self.flashDump.setObjectName("flashDump")
        self.updateFWText = QtWidgets.QTextEdit(self.touchGroupBox)
        self.updateFWText.setGeometry(QtCore.QRect(290, 50, 80, 30))
        self.updateFWText.setMaximumSize(QtCore.QSize(100, 30))
        self.updateFWText.setStyleSheet("color: rgb(0, 0, 0);")
        self.updateFWText.setObjectName("updateFWText")
        self.reset = QtWidgets.QPushButton(self.touchGroupBox)
        self.reset.setGeometry(QtCore.QRect(105, 15, 90, 30))
        self.reset.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset.setFont(font)
        self.reset.setStyleSheet("color: rgb(0, 0, 0);")
        self.reset.setObjectName("reset")
        self.updateFW = QtWidgets.QPushButton(self.touchGroupBox)
        self.updateFW.setGeometry(QtCore.QRect(200, 50, 90, 30))
        self.updateFW.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateFW.setFont(font)
        self.updateFW.setStyleSheet("color: rgb(0, 0, 0);")
        self.updateFW.setObjectName("updateFW")
        self.diagArrText = QtWidgets.QLineEdit(self.touchGroupBox)
        self.diagArrText.setGeometry(QtCore.QRect(100, 50, 80, 30))
        self.diagArrText.setObjectName("diagArrText")
        self.debugType = QtWidgets.QPushButton(self.touchGroupBox)
        self.debugType.setGeometry(QtCore.QRect(390, 50, 90, 30))
        self.debugType.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.debugType.setFont(font)
        self.debugType.setStyleSheet("color: rgb(0, 0, 0);")
        self.debugType.setObjectName("debugType")
        self.debugComboBox = QtWidgets.QComboBox(self.touchGroupBox)
        self.debugComboBox.setGeometry(QtCore.QRect(480, 51, 90, 28))
        self.debugComboBox.setCurrentText("")
        self.debugComboBox.setObjectName("debugComboBox")
        self.displayGroupBox = QtWidgets.QGroupBox(self.tabOptions)
        self.displayGroupBox.setGeometry(QtCore.QRect(0, 220, 580, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.displayGroupBox.setFont(font)
        self.displayGroupBox.setAutoFillBackground(False)
        self.displayGroupBox.setStyleSheet("color: rgb(0, 0, 255);")
        self.displayGroupBox.setObjectName("displayGroupBox")
        self.openBlight = QtWidgets.QPushButton(self.displayGroupBox)
        self.openBlight.setGeometry(QtCore.QRect(200, 15, 90, 30))
        self.openBlight.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openBlight.setFont(font)
        self.openBlight.setStyleSheet("color: rgb(0, 0, 0);")
        self.openBlight.setObjectName("openBlight")
        self.d1129 = QtWidgets.QPushButton(self.displayGroupBox)
        self.d1129.setGeometry(QtCore.QRect(10, 15, 90, 30))
        self.d1129.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.d1129.setFont(font)
        self.d1129.setStyleSheet("color: rgb(0, 0, 0);")
        self.d1129.setObjectName("d1129")
        self.d2810 = QtWidgets.QPushButton(self.displayGroupBox)
        self.d2810.setGeometry(QtCore.QRect(105, 15, 90, 30))
        self.d2810.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.d2810.setFont(font)
        self.d2810.setStyleSheet("color: rgb(0, 0, 0);")
        self.d2810.setObjectName("d2810")
        self.showRawdataUI = QtWidgets.QPushButton(self.displayGroupBox)
        self.showRawdataUI.setGeometry(QtCore.QRect(430, 15, 150, 30))
        self.showRawdataUI.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showRawdataUI.setFont(font)
        self.showRawdataUI.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.showRawdataUI.setObjectName("showRawdataUI")
        self.rawdataShowText = QtWidgets.QTextBrowser(self.tabOptions)
        self.rawdataShowText.setGeometry(QtCore.QRect(10, 268, 570, 160))
        self.rawdataShowText.setMaximumSize(QtCore.QSize(700, 205))
        self.rawdataShowText.setObjectName("rawdataShowText")
        self.TabMainWindow.addTab(self.tabOptions, "")
        self.tabRWRegister = QtWidgets.QWidget()
        self.tabRWRegister.setObjectName("tabRWRegister")
        self.pushButtonRead = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRead.setGeometry(QtCore.QRect(0, 0, 100, 25))
        self.pushButtonRead.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonRead.setFont(font)
        self.pushButtonRead.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.textEditReadRegAddr = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditReadRegAddr.setGeometry(QtCore.QRect(0, 27, 100, 101))
        self.textEditReadRegAddr.setMaximumSize(QtCore.QSize(150, 170))
        self.textEditReadRegAddr.setObjectName("textEditReadRegAddr")
        self.textEditWriteVal3 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteVal3.setGeometry(QtCore.QRect(350, 90, 120, 25))
        self.textEditWriteVal3.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal3.setObjectName("textEditWriteVal3")
        self.textEditWriteVal4 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteVal4.setGeometry(QtCore.QRect(350, 120, 120, 25))
        self.textEditWriteVal4.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal4.setObjectName("textEditWriteVal4")
        self.textEditWriteVal2 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteVal2.setGeometry(QtCore.QRect(350, 60, 120, 25))
        self.textEditWriteVal2.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal2.setObjectName("textEditWriteVal2")
        self.textEditWriteAddr1 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteAddr1.setGeometry(QtCore.QRect(220, 30, 120, 25))
        self.textEditWriteAddr1.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr1.setObjectName("textEditWriteAddr1")
        self.textEditWriteAddr2 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteAddr2.setGeometry(QtCore.QRect(220, 60, 120, 25))
        self.textEditWriteAddr2.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr2.setObjectName("textEditWriteAddr2")
        self.textEditWriteAddr0 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteAddr0.setGeometry(QtCore.QRect(220, 0, 120, 25))
        self.textEditWriteAddr0.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr0.setObjectName("textEditWriteAddr0")
        self.textEditWriteVal1 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteVal1.setGeometry(QtCore.QRect(350, 30, 120, 25))
        self.textEditWriteVal1.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal1.setObjectName("textEditWriteVal1")
        self.pushButtonRegWrite0 = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRegWrite0.setGeometry(QtCore.QRect(110, 0, 100, 25))
        self.pushButtonRegWrite0.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite0.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonRegWrite0.setObjectName("pushButtonRegWrite0")
        self.pushButtonRegWrite1 = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRegWrite1.setGeometry(QtCore.QRect(110, 30, 100, 25))
        self.pushButtonRegWrite1.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite1.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonRegWrite1.setObjectName("pushButtonRegWrite1")
        self.textEditWriteVal0 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteVal0.setGeometry(QtCore.QRect(350, 0, 120, 25))
        self.textEditWriteVal0.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteVal0.setObjectName("textEditWriteVal0")
        self.textEditWriteAddr3 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteAddr3.setGeometry(QtCore.QRect(220, 90, 120, 25))
        self.textEditWriteAddr3.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr3.setObjectName("textEditWriteAddr3")
        self.pushButtonRegWrite2 = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRegWrite2.setGeometry(QtCore.QRect(110, 60, 100, 25))
        self.pushButtonRegWrite2.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonRegWrite2.setObjectName("pushButtonRegWrite2")
        self.textEditWriteAddr4 = QtWidgets.QTextEdit(self.tabRWRegister)
        self.textEditWriteAddr4.setGeometry(QtCore.QRect(220, 120, 120, 25))
        self.textEditWriteAddr4.setMaximumSize(QtCore.QSize(150, 30))
        self.textEditWriteAddr4.setObjectName("textEditWriteAddr4")
        self.pushButtonRegWrite4 = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRegWrite4.setGeometry(QtCore.QRect(110, 120, 100, 25))
        self.pushButtonRegWrite4.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonRegWrite4.setObjectName("pushButtonRegWrite4")
        self.pushButtonRegWrite3 = QtWidgets.QPushButton(self.tabRWRegister)
        self.pushButtonRegWrite3.setGeometry(QtCore.QRect(110, 90, 100, 25))
        self.pushButtonRegWrite3.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButtonRegWrite3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonRegWrite3.setObjectName("pushButtonRegWrite3")
        self.tpReglengthLabel = QtWidgets.QLabel(self.tabRWRegister)
        self.tpReglengthLabel.setGeometry(QtCore.QRect(5, 128, 50, 20))
        self.tpReglengthLabel.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tpReglengthLabel.setFont(font)
        self.tpReglengthLabel.setStyleSheet("color: rgb(0, 85, 255);")
        self.tpReglengthLabel.setObjectName("tpReglengthLabel")
        self.reglength = QtWidgets.QComboBox(self.tabRWRegister)
        self.reglength.setGeometry(QtCore.QRect(70, 128, 30, 20))
        self.reglength.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.reglength.setObjectName("reglength")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.reglength.addItem("")
        self.readRegValShowText = QtWidgets.QTextBrowser(self.tabRWRegister)
        self.readRegValShowText.setGeometry(QtCore.QRect(0, 150, 585, 280))
        self.readRegValShowText.setMinimumSize(QtCore.QSize(0, 0))
        self.readRegValShowText.setMaximumSize(QtCore.QSize(670, 300))
        self.readRegValShowText.setObjectName("readRegValShowText")
        self.TabMainWindow.addTab(self.tabRWRegister, "")
        self.tabDDRegister = QtWidgets.QWidget()
        self.tabDDRegister.setObjectName("tabDDRegister")
        self.ddRegGroupBox1 = QtWidgets.QGroupBox(self.tabDDRegister)
        self.ddRegGroupBox1.setGeometry(QtCore.QRect(0, 0, 675, 129))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ddRegGroupBox1.setFont(font)
        self.ddRegGroupBox1.setStyleSheet("color: rgb(255, 0, 0);")
        self.ddRegGroupBox1.setObjectName("ddRegGroupBox1")
        self.G1DDRead = QtWidgets.QPushButton(self.ddRegGroupBox1)
        self.G1DDRead.setGeometry(QtCore.QRect(0, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G1DDRead.setFont(font)
        self.G1DDRead.setObjectName("G1DDRead")
        self.G1AddrlineEdit = QtWidgets.QLineEdit(self.ddRegGroupBox1)
        self.G1AddrlineEdit.setGeometry(QtCore.QRect(80, 16, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G1AddrlineEdit.setFont(font)
        self.G1AddrlineEdit.setObjectName("G1AddrlineEdit")
        self.G1DDWrite = QtWidgets.QPushButton(self.ddRegGroupBox1)
        self.G1DDWrite.setGeometry(QtCore.QRect(200, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G1DDWrite.setFont(font)
        self.G1DDWrite.setObjectName("G1DDWrite")
        self.G1DDClear = QtWidgets.QPushButton(self.ddRegGroupBox1)
        self.G1DDClear.setGeometry(QtCore.QRect(500, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G1DDClear.setFont(font)
        self.G1DDClear.setObjectName("G1DDClear")
        self.G1DDCopy = QtWidgets.QPushButton(self.ddRegGroupBox1)
        self.G1DDCopy.setGeometry(QtCore.QRect(420, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G1DDCopy.setFont(font)
        self.G1DDCopy.setObjectName("G1DDCopy")
        self.ddRegGroupBox2 = QtWidgets.QGroupBox(self.tabDDRegister)
        self.ddRegGroupBox2.setGeometry(QtCore.QRect(0, 140, 675, 129))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ddRegGroupBox2.setFont(font)
        self.ddRegGroupBox2.setStyleSheet("")
        self.ddRegGroupBox2.setObjectName("ddRegGroupBox2")
        self.G2DDRead = QtWidgets.QPushButton(self.ddRegGroupBox2)
        self.G2DDRead.setGeometry(QtCore.QRect(0, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G2DDRead.setFont(font)
        self.G2DDRead.setObjectName("G2DDRead")
        self.G2AddrlineEdit = QtWidgets.QLineEdit(self.ddRegGroupBox2)
        self.G2AddrlineEdit.setGeometry(QtCore.QRect(80, 16, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G2AddrlineEdit.setFont(font)
        self.G2AddrlineEdit.setObjectName("G2AddrlineEdit")
        self.G2DDWrite = QtWidgets.QPushButton(self.ddRegGroupBox2)
        self.G2DDWrite.setGeometry(QtCore.QRect(200, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G2DDWrite.setFont(font)
        self.G2DDWrite.setObjectName("G2DDWrite")
        self.G2DDClear = QtWidgets.QPushButton(self.ddRegGroupBox2)
        self.G2DDClear.setGeometry(QtCore.QRect(500, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G2DDClear.setFont(font)
        self.G2DDClear.setObjectName("G2DDClear")
        self.G2DDCopy = QtWidgets.QPushButton(self.ddRegGroupBox2)
        self.G2DDCopy.setGeometry(QtCore.QRect(420, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G2DDCopy.setFont(font)
        self.G2DDCopy.setObjectName("G2DDCopy")
        self.ddRegGroupBox3 = QtWidgets.QGroupBox(self.tabDDRegister)
        self.ddRegGroupBox3.setGeometry(QtCore.QRect(0, 290, 675, 129))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ddRegGroupBox3.setFont(font)
        self.ddRegGroupBox3.setStyleSheet("color: rgb(0, 0, 255);")
        self.ddRegGroupBox3.setObjectName("ddRegGroupBox3")
        self.G3DDRead = QtWidgets.QPushButton(self.ddRegGroupBox3)
        self.G3DDRead.setGeometry(QtCore.QRect(0, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G3DDRead.setFont(font)
        self.G3DDRead.setObjectName("G3DDRead")
        self.G3AddrlineEdit = QtWidgets.QLineEdit(self.ddRegGroupBox3)
        self.G3AddrlineEdit.setGeometry(QtCore.QRect(80, 16, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G3AddrlineEdit.setFont(font)
        self.G3AddrlineEdit.setObjectName("G3AddrlineEdit")
        self.G3DDWrite = QtWidgets.QPushButton(self.ddRegGroupBox3)
        self.G3DDWrite.setGeometry(QtCore.QRect(200, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G3DDWrite.setFont(font)
        self.G3DDWrite.setObjectName("G3DDWrite")
        self.G3DDClear = QtWidgets.QPushButton(self.ddRegGroupBox3)
        self.G3DDClear.setGeometry(QtCore.QRect(500, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G3DDClear.setFont(font)
        self.G3DDClear.setObjectName("G3DDClear")
        self.G3DDCopy = QtWidgets.QPushButton(self.ddRegGroupBox3)
        self.G3DDCopy.setGeometry(QtCore.QRect(420, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.G3DDCopy.setFont(font)
        self.G3DDCopy.setObjectName("G3DDCopy")
        self.TabMainWindow.addTab(self.tabDDRegister, "")
        self.tabDDLog = QtWidgets.QWidget()
        self.tabDDLog.setObjectName("tabDDLog")
        self.DDreadRegValShowText = QtWidgets.QTextBrowser(self.tabDDLog)
        self.DDreadRegValShowText.setGeometry(QtCore.QRect(0, 1, 585, 430))
        self.DDreadRegValShowText.setMinimumSize(QtCore.QSize(0, 0))
        self.DDreadRegValShowText.setMaximumSize(QtCore.QSize(675, 700))
        self.DDreadRegValShowText.setObjectName("DDreadRegValShowText")
        self.TabMainWindow.addTab(self.tabDDLog, "")
        self.horizontalLayout.addWidget(self.TabMainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabMainWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADB Monitor 2.0.0"))
        self.touchInfoGroupBox.setTitle(_translate("MainWindow", "Touch info"))
        self.touchInfoRXLineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.touchInfoTXLineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.touchInfoRXLabel.setText(_translate("MainWindow", "RX:"))
        self.touchInfoTXLabel.setText(_translate("MainWindow", "TX:"))
        self.touchInfoRexYLabel.setText(_translate("MainWindow", "Res Y:"))
        self.touchInfoRexXLabel.setText(_translate("MainWindow", "Res X:"))
        self.touchInfoResXLineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.touchInfoResYLineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Path settings"))
        self.pathV1RadioButton.setText(_translate("MainWindow", "V1"))
        self.pathV2RadioButton.setText(_translate("MainWindow", "V2"))
        self.pathDriVerLabel.setText(_translate("MainWindow", "Driver version:"))
        self.pathDiagLabel.setText(_translate("MainWindow", "Diag:"))
        self.pathRegLabel.setText(_translate("MainWindow", "Reg:"))
        self.pathResetLabel.setText(_translate("MainWindow", "Reset:"))
        self.pathIntenLabel.setText(_translate("MainWindow", "Int_en:"))
        self.pathDiagarrLabel.setText(_translate("MainWindow", "Diag_arr:"))
        self.pathSenseonoffLabel.setText(_translate("MainWindow", "SenseOnOff:"))
        self.pathStackLabel.setText(_translate("MainWindow", "stack:"))
        self.pathDebugLabel.setText(_translate("MainWindow", "Debug:"))
        self.pathSelftestLabel.setText(_translate("MainWindow", "SelfTest:"))
        self.pathFlashdumpLabel.setText(_translate("MainWindow", "Flash_dump:"))
        self.pathHXFolderLabel.setText(_translate("MainWindow", "HX folder:"))
        self.pathFWLabel.setText(_translate("MainWindow", "FW path:"))
        self.pathConmmentLabel.setText(_translate("MainWindow", "(New project you need choose v1/v2)"))
        self.groupBox.setTitle(_translate("MainWindow", "Project"))
        self.conmment.setText(_translate("MainWindow", "New project:"))
        self.pathSavePushButton.setText(_translate("MainWindow", "Save as a project"))
        self.conmment_2.setText(_translate("MainWindow", "Select project:"))
        self.settingRemove.setText(_translate("MainWindow", "Remove"))
        self.settingRemoveLabel.setText(_translate("MainWindow", "Del project"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.wifiGroupBox.setTitle(_translate("MainWindow", "WIFI"))
        self.wifiConnect.setText(_translate("MainWindow", "Connect"))
        self.wifiDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.wifiReconnect.setText(_translate("MainWindow", "Reconnect"))
        self.wifiStatus.setText(_translate("MainWindow", "WiFi Status"))
        self.root.setText(_translate("MainWindow", "Root"))
        self.adbStatus.setText(_translate("MainWindow", "ADB Status"))
        self.adbGroupBox.setTitle(_translate("MainWindow", "ADB"))
        self.homekey.setText(_translate("MainWindow", "Home"))
        self.reboot.setText(_translate("MainWindow", "Reboot"))
        self.volDown.setText(_translate("MainWindow", "Vol down"))
        self.backkey.setText(_translate("MainWindow", "Back"))
        self.volUp.setText(_translate("MainWindow", "Vol up"))
        self.powerKey.setText(_translate("MainWindow", "PowerKey"))
        self.screenShot.setText(_translate("MainWindow", "ScreenShot"))
        self.openClosePoint.setText(_translate("MainWindow", "OpenPoint"))
        self.opencmd.setText(_translate("MainWindow", "Open cmd"))
        self.hideShowVirtual.setText(_translate("MainWindow", "ShowVirtual"))
        self.shutDown.setText(_translate("MainWindow", "ShutDown"))
        self.screenRecord.setText(_translate("MainWindow", "ScreenRecord"))
        self.touchGroupBox.setTitle(_translate("MainWindow", "Touch"))
        self.inten0.setText(_translate("MainWindow", "Int_en"))
        self.senseon.setText(_translate("MainWindow", "SenseOn"))
        self.fwVersion.setText(_translate("MainWindow", "FWVersion"))
        self.selftest.setText(_translate("MainWindow", "SelfTest"))
        self.diagArr.setText(_translate("MainWindow", "DiagArr"))
        self.flashDump.setText(_translate("MainWindow", "FlashDump"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.updateFW.setText(_translate("MainWindow", "UpdateFW"))
        self.diagArrText.setPlaceholderText(_translate("MainWindow", "Default:6"))
        self.debugType.setText(_translate("MainWindow", "Debug"))
        self.displayGroupBox.setTitle(_translate("MainWindow", "Display"))
        self.openBlight.setText(_translate("MainWindow", "OpenBlight"))
        self.d1129.setText(_translate("MainWindow", "1129"))
        self.d2810.setText(_translate("MainWindow", "2810"))
        self.showRawdataUI.setText(_translate("MainWindow", "Show Rawdata UI"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.tabOptions), _translate("MainWindow", "Options"))
        self.pushButtonRead.setText(_translate("MainWindow", "Read"))
        self.pushButtonRegWrite0.setText(_translate("MainWindow", "Write 0"))
        self.pushButtonRegWrite1.setText(_translate("MainWindow", "Write 1"))
        self.pushButtonRegWrite2.setText(_translate("MainWindow", "Write 2"))
        self.pushButtonRegWrite4.setText(_translate("MainWindow", "Write 4"))
        self.pushButtonRegWrite3.setText(_translate("MainWindow", "Write 3"))
        self.tpReglengthLabel.setText(_translate("MainWindow", "Length"))
        self.reglength.setItemText(0, _translate("MainWindow", "1"))
        self.reglength.setItemText(1, _translate("MainWindow", "2"))
        self.reglength.setItemText(2, _translate("MainWindow", "3"))
        self.reglength.setItemText(3, _translate("MainWindow", "4"))
        self.reglength.setItemText(4, _translate("MainWindow", "5"))
        self.reglength.setItemText(5, _translate("MainWindow", "6"))
        self.reglength.setItemText(6, _translate("MainWindow", "7"))
        self.reglength.setItemText(7, _translate("MainWindow", "8"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.tabRWRegister), _translate("MainWindow", "TP Reg"))
        self.ddRegGroupBox1.setTitle(_translate("MainWindow", "Group 1"))
        self.G1DDRead.setText(_translate("MainWindow", "Read"))
        self.G1AddrlineEdit.setPlaceholderText(_translate("MainWindow", "Eg:B9000A"))
        self.G1DDWrite.setText(_translate("MainWindow", "Write"))
        self.G1DDClear.setText(_translate("MainWindow", "Clear"))
        self.G1DDCopy.setText(_translate("MainWindow", "Copy"))
        self.ddRegGroupBox2.setTitle(_translate("MainWindow", "Group 2"))
        self.G2DDRead.setText(_translate("MainWindow", "Read"))
        self.G2AddrlineEdit.setPlaceholderText(_translate("MainWindow", "Eg:B9000A"))
        self.G2DDWrite.setText(_translate("MainWindow", "Write"))
        self.G2DDClear.setText(_translate("MainWindow", "Clear"))
        self.G2DDCopy.setText(_translate("MainWindow", "Copy"))
        self.ddRegGroupBox3.setTitle(_translate("MainWindow", "Group 3"))
        self.G3DDRead.setText(_translate("MainWindow", "Read"))
        self.G3AddrlineEdit.setPlaceholderText(_translate("MainWindow", "Eg:B9000A"))
        self.G3DDWrite.setText(_translate("MainWindow", "Write"))
        self.G3DDClear.setText(_translate("MainWindow", "Clear"))
        self.G3DDCopy.setText(_translate("MainWindow", "Copy"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.tabDDRegister), _translate("MainWindow", "DD Reg"))
        self.TabMainWindow.setTabText(self.TabMainWindow.indexOf(self.tabDDLog), _translate("MainWindow", "Log"))
